server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: doctor-service
          uri: http://localhost:8082
          predicates:
            - Path=/doctors/**
        - id: appointments-service
          uri: http://localhost:8083
          predicates:
            - Path=/appointments/**
        - id: patients-service
          uri: http://localhost:8084
          predicates:
            - Path=/patients/**